Better constant names.

diff --git a/s3-upload b/s3-upload
--- a/s3-upload
+++ b/s3-upload
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-# Default config file
-S3_CONFIG_FILE=${S3_CONFIG_FILE:-"$HOME/.config/s3-upload"}
+# Config defaults
+S3_UPLOAD_CONFIG_FILE=${S3_UPLOAD_CONFIG_FILE:-"$HOME/.config/s3-upload"}
+COPY=
+NOTIFY=
+QUIET=
+CLIPBOARD=
 
 # Load config
-if [ -f "$S3_CONFIG_FILE" ]; then
-  . "$S3_CONFIG_FILE"
+if [ -f "$S3_UPLOAD_CONFIG_FILE" ]; then
+  . "$S3_UPLOAD_CONFIG_FILE"
 fi
 
 # Die if any errors happen
@@ -130,8 +134,8 @@ while [[ $# -gt 0 ]]; do
   case "${END_OF_OPT}${1}" in
     -h|--help)      usage 0 ;;
     -c|--config)    shift; . "$1" ;;
-    -p|--secret)    shift; S3_ACCESS_KEY="$1" ;;
-    -k|--key)       shift; S3_SECRET_KEY="$1" ;;
+    -p|--secret)    shift; AWS_ACCESS_KEY_ID="$1" ;;
+    -k|--key)       shift; AWS_ACCESS_KEY_SECRET="$1" ;;
     -n|--name)      shift; names+=("$1") ;;
     -t|--type)      shift; mimetypes+=("$1") ;;
     -q|--quiet)     QUIET=1 ;;
@@ -163,7 +167,7 @@ if [ -z "$CLIPBOARD" ] && [ -n "$COPY" ]; then
 fi
 
 # First run...
-if [ -z "${S3_ACCESS_KEY}${S3_SECRET_KEY}${S3_BUCKET_NAME}" -a ! -f "$S3_CONFIG_FILE" ]; then
+if [ -z "${AWS_ACCESS_KEY_ID}${AWS_ACCESS_KEY_SECRET}${S3_BUCKET_NAME}" -a ! -f "$S3_UPLOAD_CONFIG_FILE" ]; then
 
   # Make sure we have an interactive terminal
   if [[ ! -t 1 ]] || [[ -n "$QUIET" ]]; then
@@ -183,13 +187,13 @@ if [ -z "${S3_ACCESS_KEY}${S3_SECRET_KEY}${S3_BUCKET_NAME}" -a ! -f "$S3_CONFIG_
     https://s3.console.aws.amazon.com/s3/home
 
   " >&2
-  read -p "  ${bold}S3 Access Key:${normal} " S3_ACCESS_KEY
-  read -p "  ${bold}S3 Secret Key:${normal} " S3_SECRET_KEY
+  read -p "  ${bold}S3 Access Key:${normal} " AWS_ACCESS_KEY_ID
+  read -p "  ${bold}S3 Secret Key:${normal} " AWS_ACCESS_KEY_SECRET
   read -p "  ${bold}S3 Bucket Name:${normal} " S3_BUCKET_NAME
-  echo "S3_ACCESS_KEY='$S3_ACCESS_KEY'" > "$S3_CONFIG_FILE"
-  echo "S3_SECRET_KEY='$S3_SECRET_KEY'" >> "$S3_CONFIG_FILE"
-  echo "S3_BUCKET_NAME='$S3_BUCKET_NAME'" >> "$S3_CONFIG_FILE"
-  chmod 600 "$S3_CONFIG_FILE"
+  echo "AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID'" > "$S3_UPLOAD_CONFIG_FILE"
+  echo "AWS_ACCESS_KEY_SECRET='$AWS_ACCESS_KEY_SECRET'" >> "$S3_UPLOAD_CONFIG_FILE"
+  echo "S3_BUCKET_NAME='$S3_BUCKET_NAME'" >> "$S3_UPLOAD_CONFIG_FILE"
+  chmod 600 "$S3_UPLOAD_CONFIG_FILE"
 
   echo '
 
@@ -236,14 +240,14 @@ elif [ -z "$*" ]; then
 fi
 
 # Require username
-if [ -z "$S3_ACCESS_KEY" ]; then
-  echo "Error: missing S3_ACCESS_KEY" >&2
+if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+  echo "Error: missing AWS_ACCESS_KEY_ID" >&2
   exit 1
 fi
 
 # Require password
-if [ -z "$S3_SECRET_KEY" ]; then
-  read -p 'S3 Secret Key: ' S3_SECRET_KEY
+if [ -z "$AWS_ACCESS_KEY_SECRET" ]; then
+  read -p 'S3 Secret Key: ' AWS_ACCESS_KEY_SECRET
 fi
 
 # Require Bucket
@@ -277,7 +281,7 @@ upload() {
   local contentType="${contentType:-"application/octet-stream"}"
   local dateValue=`date -R`
   local stringToSign="PUT\n\n${contentType}\n${dateValue}\n${resource}"
-  local signature="$(echo -en "${stringToSign}" | openssl sha1 -hmac "${S3_SECRET_KEY}" -binary | base64)"
+  local signature="$(echo -en "${stringToSign}" | openssl sha1 -hmac "${AWS_ACCESS_KEY_SECRET}" -binary | base64)"
   local url="https://${S3_BUCKET_NAME}.s3.amazonaws.com/${filename}"
   local input=/dev/null
   if [[ "$file" == '-' ]]; then
@@ -289,7 +293,7 @@ upload() {
     -H "Host: ${S3_BUCKET_NAME}.s3.amazonaws.com" \
     -H "Date: ${dateValue}" \
     -H "Content-Type: ${contentType}" \
-    -H "Authorization: AWS ${S3_ACCESS_KEY}:${signature}" \
+    -H "Authorization: AWS ${AWS_ACCESS_KEY_ID}:${signature}" \
     "$url" < "$input"
 
   # Print result
